flac_s -8Vep -f learning_is_the_new_literacy.wav -o learning_is_the_new_literacy1.flac --mid-side --replay-gain --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.learning_is_the_new_literacy1.flac.out 2>> flac.learning_is_the_new_literacy1.flac.err
flac_s -7Vep -f learning_is_the_new_literacy.wav -o learning_is_the_new_literacy2.flac --mid-side --replay-gain --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.learning_is_the_new_literacy2.flac.out 2>> flac.learning_is_the_new_literacy2.flac.err
flac_s -6Vep -f learning_is_the_new_literacy.wav -o learning_is_the_new_literacy3.flac --replay-gain --adaptive-mid-side --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.learning_is_the_new_literacy3.flac.out 2>> flac.learning_is_the_new_literacy3.flac.err
flac_s -8Vep -f compiler_puzzles.wav -o compiler_puzzles1.flac --replay-gain --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.compiler_puzzles1.flac.out 2>> flac.compiler_puzzles1.flac.err
flac_s -7Vep -f compiler_puzzles.wav -o compiler_puzzles2.flac --adaptive-mid-side --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.compiler_puzzles2.flac.out 2>> flac.compiler_puzzles2.flac.err
flac_s -6Vep -f compiler_puzzles.wav -o compiler_puzzles3.flac --replay-gain --adaptive-mid-side --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.compiler_puzzles3.flac.out 2>> flac.compiler_puzzles3.flac.err
flac_s -8Vep -f git_etiquette_stereo.wav -o git_etiquette_stereo1.flac --mid-side --replay-gain --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.git_etiquette_stereo1.flac.out 2>> flac.git_etiquette_stereo1.flac.err
flac_s -7Vep -f git_etiquette_stereo.wav -o git_etiquette_stereo2.flac --mid-side --replay-gain --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.git_etiquette_stereo2.flac.out 2>> flac.git_etiquette_stereo2.flac.err
flac_s -6Vep -f git_etiquette_stereo.wav -o git_etiquette_stereo3.flac --adaptive-mid-side --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.git_etiquette_stereo3.flac.out 2>> flac.git_etiquette_stereo3.flac.err
flac_s -8Vep -f working_for_your_team.wav -o working_for_your_team1.flac --mid-side --replay-gain --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.working_for_your_team1.flac.out 2>> flac.working_for_your_team1.flac.err
flac_s -7Vep -f working_for_your_team.wav -o working_for_your_team2.flac --mid-side --replay-gain --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.working_for_your_team2.flac.out 2>> flac.working_for_your_team2.flac.err
flac_s -6Vep -f working_for_your_team.wav -o working_for_your_team3.flac --replay-gain --adaptive-mid-side --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.working_for_your_team3.flac.out 2>> flac.working_for_your_team3.flac.err
flac_s -8Vep -f designing_a_motherboard.wav -o designing_a_motherboard1.flac --mid-side --replay-gain --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.designing_a_motherboard1.flac.out 2>> flac.designing_a_motherboard1.flac.err
flac_s -7Vep -f designing_a_motherboard.wav -o designing_a_motherboard2.flac --mid-side -r 2 --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.designing_a_motherboard2.flac.out 2>> flac.designing_a_motherboard2.flac.err
flac_s -6Vep -f designing_a_motherboard.wav -o designing_a_motherboard3.flac --max-lpc-order=10 --replay-gain --keep-foreign-metadata --no-preserve-modtime -j 4 > flac.designing_a_motherboard3.flac.out 2>> flac.designing_a_motherboard3.flac.err
flac_s -t -f *.flac --no-silent --no-decode-through-errors --delete-input-file -j 4 > flac.--no-decode-through-errors.out 2>> flac.--no-decode-through-errors.err
